2024/08/24 23:43:54.830886 User with that login already exists!
2024/08/24 23:44:42.251979 User with that login already exists!
2024/09/08 23:39:27.417912 Error in repository(CreateUser):ОШИБКА: ошибка синтаксиса (примерное положение: ",") (SQLSTATE 42601)
2024/09/08 23:55:49.145002 Error in repository(CreateUser):ОШИБКА: INSERT или UPDATE в таблице "users" нарушает ограничение внешнего ключа "fk_users_role" (SQLSTATE 23503)
2024/09/27 11:40:29.299136 Error in repository (GetUniById):  record not found
2024/09/27 11:41:05.993121 Error in repository (GetUniById):  record not found
2024/09/27 11:54:58.133243 Error in repository (GetUniById):  record not found
2024/09/27 12:05:47.573592 Error in repository (GetUniById):  record not found
2024/09/27 12:06:00.564470 Error in repository (GetUniById):  record not found
2024/10/05 21:15:52.845715 db.setupPostgresProduction err: failed to connect to `host=port= user=dbname= database=`: hostname resolving error (lookup port=: no such host)
2024/10/05 21:38:16.011684 db.setupPostgresProduction err: failed to connect to `host=port= user=dbname= database=`: hostname resolving error (lookup port=: no such host)
2024/10/05 21:39:20.507894 db.setupPostgresProduction err: failed to connect to `host=port= user=dbname= database=`: hostname resolving error (lookup port=: no such host)
2024/10/05 21:40:40.373275 db.setupPostgresProduction err: failed to connect to `host=port= user=dbname= database=`: hostname resolving error (lookup port=: no such host)
2024/10/05 21:45:54.398618 db.setupPostgresProduction err: failed to connect to `host=port= user=dbname= database=`: hostname resolving error (lookup port=: no such host)
2024/10/05 21:46:21.170240 db.setupPostgresProduction err: failed to connect to `host=port= user=dbname= database=`: hostname resolving error (lookup port=: no such host)
2024/10/05 21:53:15.180560 db.setupPostgresProduction err: failed to connect to `host=port= user=dbname= database=`: hostname resolving error (lookup port=: no such host)
2024/10/06 02:39:29.492256 db.setupPostgresProduction err: failed to connect to `host=port= user=dbname= database=`: hostname resolving error (lookup port=: no such host)
2024/10/14 20:47:59.602118 Error in repository(CreateUser):unsupported data type: 0xc000008228: Table not set, please set it like: db.Model(&user) or db.Table("users")
2024/10/14 20:48:12.014356 Error in repository(CreateUser):unsupported data type: 0xc0004a89d8: Table not set, please set it like: db.Model(&user) or db.Table("users")
2024/10/14 20:49:12.113182 Error in repository(CreateUser):sql: expected 2 destination arguments in Scan, not 1
2024/10/14 20:50:01.449751 Error in repository(CreateUser):sql: expected 2 destination arguments in Scan, not 1
2024/10/14 20:50:17.690364 Error in repository(CreateUser):ОШИБКА: INSERT или UPDATE в таблице "users" нарушает ограничение внешнего ключа "fk_users_role" (SQLSTATE 23503)
2024/10/14 20:51:55.984457 Error in repository(CreateUser):ОШИБКА: INSERT или UPDATE в таблице "users" нарушает ограничение внешнего ключа "fk_users_city" (SQLSTATE 23503)
2024/10/14 20:53:22.967614 Error in repository(CreateUser):ОШИБКА: INSERT или UPDATE в таблице "users" нарушает ограничение внешнего ключа "fk_users_city" (SQLSTATE 23503)
2024/10/14 20:56:10.324939 Error in repository(CreateUser):ОШИБКА: INSERT или UPDATE в таблице "users" нарушает ограничение внешнего ключа "fk_users_role" (SQLSTATE 23503)
2024/10/14 20:57:19.655178 Error in repository(CreateUser): ОШИБКА: INSERT или UPDATE в таблице "users" нарушает ограничение внешнего ключа "fk_users_role" (SQLSTATE 23503)
2024/10/14 20:57:25.735239 Error in repository(CreateUser): ОШИБКА: INSERT или UPDATE в таблице "users" нарушает ограничение внешнего ключа "fk_users_city" (SQLSTATE 23503)
2024/10/14 21:02:29.778027 Error in repository(CreateUser): ОШИБКА: INSERT или UPDATE в таблице "users" нарушает ограничение внешнего ключа "fk_users_role" (SQLSTATE 23503)
2024/10/14 21:02:35.862493 Error in repository(CreateUser): ОШИБКА: INSERT или UPDATE в таблице "users" нарушает ограничение внешнего ключа "fk_users_city" (SQLSTATE 23503)
2024/10/14 21:02:45.471031 Error in repository(CreateUser): ОШИБКА: INSERT или UPDATE в таблице "users" нарушает ограничение внешнего ключа "fk_users_role" (SQLSTATE 23503)
2024/10/14 21:04:37.973986 Error in repository(CreateUser): ОШИБКА: INSERT или UPDATE в таблице "users" нарушает ограничение внешнего ключа "fk_users_city" (SQLSTATE 23503)
2024/10/14 21:05:49.043830 Not found in(CreateUser): record not found
2024/10/14 21:06:38.563791 Not found in(CreateUser): record not found
